language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "8"
      env: NO_SAUCE=true
    - node_js: "7"
      env: NO_SAUCE=true
notifications:
  slack:
    rooms:
      - altenter-project:Pc8sMyCuHNPBCg1TOw0weD9S#tech
addons:
  sauce_connect:
    username: "Gerkin"
    access_key: "bcc962ee-af76-4e36-bf15-ce3cbbbb5b8c"
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
cache:
  directories:
    - "node_modules"