language: node_js
node_js:
  - "node"
  - "8"
  - "7"
notifications:
  slack:
    rooms:
      - altenter-project:Pc8sMyCuHNPBCg1TOw0weD9S#tech
addons:
  sauce_connect:
    username: "Gerkin"
    access_key: "bcc962ee-af76-4e36-bf15-ce3cbbbb5b8c"
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2