title: Diaspora
description: Multi-source ORM for node.js & the browser
show_downloads: true
google_analytics: UA-61219056-7
heap: "3159885702"
theme: jekyll-theme-dinky
canonical_url: https://diaspora.ithoughts.io
host: https://diaspora.ithoughts.io
port: ""
baseurl: ""
plugins:
  - jekyll-toc
#  - jekyll-minifier
destination: ../../diaspora-gh-pages
lsi: true
incremental: false
markdown: kramdown
kramdown:
  parse_block_html: true
github:
  zip_url: https://github.com/GerkinDev/Diaspora/archive/master.zip
  tar_url: https://github.com/GerkinDev/Diaspora/archive/master.tar
  repository_url: https://github.com/GerkinDev/Diaspora
  owner_url: https://github.com/GerkinDev
  clone:
	ssh: ssh+git://git@github.com:GerkinDev/Diaspora.git
